"""Builds the extra example files the guide's screenshots need, into a folder given on the command line.

Everything here is a small, synthetic stand-in written for documentation; none of it comes from a real model or a real
printer. The values mirror the repository's own installed-application acceptance suite (tools/acceptance/run.ps1).

    python fixtures.py <output-folder>
"""
import sys
import zipfile
from pathlib import Path

out = Path(sys.argv[1])
out.mkdir(parents=True, exist_ok=True)

# A project with painted colour: two objects that cannot meet on one layer, one painted with filament 2 and one with 3.
MODEL = ('<?xml version="1.0" encoding="UTF-8"?><model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">'
         '<metadata name="BambuStudio:MmPaintingVersion">1</metadata><resources>'
         '<object id="1" type="model"><mesh><vertices><vertex x="0" y="0" z="0"/><vertex x="10" y="0" z="0"/><vertex x="0" y="10" z="10"/></vertices>'
         '<triangles><triangle v1="0" v2="1" v3="2" paint_color="8"/></triangles></mesh></object>'
         '<object id="2" type="model"><mesh><vertices><vertex x="0" y="0" z="30"/><vertex x="10" y="0" z="30"/><vertex x="0" y="10" z="40"/></vertices>'
         '<triangles><triangle v1="0" v2="1" v3="2" paint_color="0C"/></triangles></mesh></object></resources>'
         '<build><item objectid="1" transform="1 0 0 0 1 0 0 0 1 0 0 0"/><item objectid="2" transform="1 0 0 0 1 0 0 0 1 0 0 0"/></build></model>')
SETTINGS = ('{"printer_model":"Snapmaker U1","filament_colour":["#FF0000","#00FF00","#0000FF","#FFFFFF"],'
            '"filament_type":["PLA","PLA","PLA","PLA"],"layer_height":"0.2","initial_layer_print_height":"0.2",'
            '"nozzle_diameter":["0.4","0.4","0.4","0.4"]}')
PARTS = ('<config><object id="1"><part id="1" subtype="normal_part"><metadata key="extruder" value="2"/></part></object>'
         '<object id="2"><part id="2" subtype="normal_part"><metadata key="extruder" value="3"/></part></object>'
         '<plate><metadata key="plater_id" value="1"/></plate></config>')
with zipfile.ZipFile(out / "example_painted.3mf", "w") as z:
    z.writestr("3D/3dmodel.model", MODEL)
    z.writestr("Metadata/project_settings.config", SETTINGS)
    z.writestr("Metadata/model_settings.config", PARTS)

# A sliced job shaped like Snapmaker Orca output for a U1.
(out / "example_sliced_job.gcode").write_text("""; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.4 on 2026-08-23 at 10:00:00
; total layer number: 12
; max_z_height: 2.40
; HEADER_BLOCK_END
; EXECUTABLE_BLOCK_START
PRINT_START
M140 S60
M104 T1 S220
SET_PRINT_STATS_INFO TOTAL_LAYER=12 CURRENT_LAYER=0
T1
;LAYER_CHANGE
;Z:0.2
G1 X10 Y10 Z0.2 F1200
;LAYER_CHANGE
;Z:0.4
G1 X20 Y20 E1.0
;LAYER_CHANGE
;Z:0.6
G1 X30 Y30 E1.0
PRINT_END
; EXECUTABLE_BLOCK_END

; filament used [mm] = 0.00, 120.00, 0.00, 0.00
; filament used [g] = 0.00, 0.36, 0.00, 0.00
; total filament used [g] = 0.36
; total layers count = 12
; estimated printing time (normal mode) = 4m 10s

; CONFIG_BLOCK_START
; filament_type = PLA;PLA;PLA;PLA
; layer_height = 0.2
; nozzle_diameter = 0.4,0.4,0.4,0.4
; printable_area = 0.5x1,270.5x1,270.5x271,0.5x271
; printer_model = Snapmaker U1
; CONFIG_BLOCK_END
""", encoding="utf-8")
print("fixtures written to", out)


# ---- placement cases for the "misplaced or oversized?" example -------------------------------------------------------
import json as _json

_CUBE_V = [(0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0), (0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1)]
_CUBE_T = [(0, 1, 2), (0, 2, 3), (4, 5, 6), (4, 6, 7), (0, 1, 5), (0, 5, 4), (2, 3, 7), (2, 7, 6), (1, 2, 6), (1, 6, 5), (0, 3, 7), (0, 7, 4)]


def _placement_3mf(name, items, printable_area=("0x0", "256x0", "256x256", "0x256")):
    """items: (object id, width, depth, height, x, y) in millimetres, written as unit cubes scaled by the build transform."""
    verts = "".join(f'<vertex x="{x}" y="{y}" z="{z}"/>' for x, y, z in _CUBE_V)
    tris = "".join(f'<triangle v1="{a}" v2="{b}" v3="{c}"/>' for a, b, c in _CUBE_T)
    res = "".join(f'<object id="{i}" type="model"><mesh><vertices>{verts}</vertices><triangles>{tris}</triangles></mesh></object>' for i, *_ in items)
    build = "".join(f'<item objectid="{i}" transform="{w} 0 0 0 {d} 0 0 0 {h} {x} {y} 0"/>' for i, w, d, h, x, y in items)
    model = ('<?xml version="1.0" encoding="UTF-8"?><model unit="millimeter" xml:lang="en-US" '
             'xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">'
             f"<resources>{res}</resources><build>{build}</build></model>")
    settings = _json.dumps({"printer_model": "Bambu Lab X1 Carbon", "printable_area": list(printable_area)})
    with zipfile.ZipFile(out / name, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("3D/3dmodel.model", model)
        z.writestr("Metadata/project_settings.config", settings)
        z.writestr("Metadata/model_settings.config", '<config><plate><metadata key="plater_id" value="1"/></plate></config>')


# one 320 mm long bar: longer than the U1's plate, so no move can bring it on
_placement_3mf("example_oversized.3mf", [(1, 320, 20, 20, 0, 100)])
# two small cubes 290 mm apart: each is small, but together they are wider than the plate
_placement_3mf("example_spread.3mf", [(1, 10, 10, 10, 5, 100), (2, 10, 10, 10, 295, 100)])

# ---- sliced jobs that tell Studio something definite -------------------------------------------------------------------
_base = (out / "example_sliced_job.gcode").read_text(encoding="utf-8")
(out / "example_other_printer.gcode").write_text(
    _base.replace("; printer_model = Snapmaker U1", "; printer_model = Bambu Lab X1 Carbon")
         .replace("; printable_area = 0.5x1,270.5x1,270.5x271,0.5x271", "; printable_area = 0x0,256x0,256x256,0x256")
         .replace("generated by Snapmaker Orca 2.3.4", "generated by OrcaSlicer 2.3.0"), encoding="utf-8")
print("placement and printer examples written")
