"""Builds the extra example files the guide's screenshots need, into a folder given on the command line.

Everything here is a small, synthetic stand-in written for documentation; none of it comes from a real model or a real
printer. The values mirror the repository's own installed-application acceptance suite (tools/acceptance/run.ps1).

    python fixtures.py <output-folder>
"""
import sys
import zipfile
from pathlib import Path

out = Path(sys.argv[1])
out.mkdir(parents=True, exist_ok=True)

# A project with painted colour: two objects that cannot meet on one layer, one painted with filament 2 and one with 3.
MODEL = ('<?xml version="1.0" encoding="UTF-8"?><model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">'
         '<metadata name="BambuStudio:MmPaintingVersion">1</metadata><resources>'
         '<object id="1" type="model"><mesh><vertices><vertex x="0" y="0" z="0"/><vertex x="10" y="0" z="0"/><vertex x="0" y="10" z="10"/></vertices>'
         '<triangles><triangle v1="0" v2="1" v3="2" paint_color="8"/></triangles></mesh></object>'
         '<object id="2" type="model"><mesh><vertices><vertex x="0" y="0" z="30"/><vertex x="10" y="0" z="30"/><vertex x="0" y="10" z="40"/></vertices>'
         '<triangles><triangle v1="0" v2="1" v3="2" paint_color="0C"/></triangles></mesh></object></resources>'
         '<build><item objectid="1" transform="1 0 0 0 1 0 0 0 1 0 0 0"/><item objectid="2" transform="1 0 0 0 1 0 0 0 1 0 0 0"/></build></model>')
SETTINGS = ('{"printer_model":"Snapmaker U1","filament_colour":["#FF0000","#00FF00","#0000FF","#FFFFFF"],'
            '"filament_type":["PLA","PLA","PLA","PLA"],"layer_height":"0.2","initial_layer_print_height":"0.2",'
            '"nozzle_diameter":["0.4","0.4","0.4","0.4"]}')
PARTS = ('<config><object id="1"><part id="1" subtype="normal_part"><metadata key="extruder" value="2"/></part></object>'
         '<object id="2"><part id="2" subtype="normal_part"><metadata key="extruder" value="3"/></part></object>'
         '<plate><metadata key="plater_id" value="1"/></plate></config>')
with zipfile.ZipFile(out / "example_painted.3mf", "w") as z:
    z.writestr("3D/3dmodel.model", MODEL)
    z.writestr("Metadata/project_settings.config", SETTINGS)
    z.writestr("Metadata/model_settings.config", PARTS)

# A sliced job shaped like Snapmaker Orca output for a U1.
(out / "example_sliced_job.gcode").write_text("""; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.4 on 2026-08-23 at 10:00:00
; total layer number: 12
; max_z_height: 2.40
; HEADER_BLOCK_END
; EXECUTABLE_BLOCK_START
PRINT_START
M140 S60
M104 T1 S220
SET_PRINT_STATS_INFO TOTAL_LAYER=12 CURRENT_LAYER=0
T1
;LAYER_CHANGE
;Z:0.2
G1 X10 Y10 Z0.2 F1200
;LAYER_CHANGE
;Z:0.4
G1 X20 Y20 E1.0
;LAYER_CHANGE
;Z:0.6
G1 X30 Y30 E1.0
PRINT_END
; EXECUTABLE_BLOCK_END

; filament used [mm] = 0.00, 120.00, 0.00, 0.00
; filament used [g] = 0.00, 0.36, 0.00, 0.00
; total filament used [g] = 0.36
; total layers count = 12
; estimated printing time (normal mode) = 4m 10s

; CONFIG_BLOCK_START
; filament_type = PLA;PLA;PLA;PLA
; layer_height = 0.2
; nozzle_diameter = 0.4,0.4,0.4,0.4
; printable_area = 0.5x1,270.5x1,270.5x271,0.5x271
; printer_model = Snapmaker U1
; CONFIG_BLOCK_END
""", encoding="utf-8")
print("fixtures written to", out)
