"""The support bundle.

Its whole value is that a user can send it to a stranger, so the tests are mostly
about what must never be in it. The redaction is asserted against values that
actually appear in a real bundle: the home directory, the username, drive-letter
paths and a printer address on the LAN.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from snapstudio_core import diagnostics


def test_redaction_removes_the_things_that_identify_a_person(monkeypatch):
    monkeypatch.setenv("USERNAME", "alexmorgan")
    payload = {
        "path": r"C:\Users\alexmorgan\Documents\secret model.3mf",
        "printer": "the printer answered at 192.168.1.240 on port 7125",
        "nested": [{"home": "/home/alexmorgan/models"}],
        "token": "X-Auth-Token abcdefghijklmnopqrstuvwxyz012345",
    }
    out = diagnostics.redact(payload)
    text = json.dumps(out)
    assert "alexmorgan" not in text
    assert "192.168.1.240" not in text
    assert "<ip>" in text
    assert "secret model.3mf" not in text          # the whole path goes, name included
    assert "abcdefghijklmnopqrstuvwxyz012345" not in text


def test_a_sha256_shaped_value_is_redacted_because_a_credential_can_look_identical():
    """This used to survive, on the reasoning that hashes are "useful and not
    secret" — but a hex-format API key or Bambuddy-style token is exactly this
    shape, and no regex can tell the two apart. Item E hardening: closed."""
    digest = "50fc5434e266f0b8c025336410534d019f8d41c0ec5190290024c702126cbf26"
    assert diagnostics.redact({"sha256": digest})["sha256"] != digest
    assert digest not in json.dumps(diagnostics.redact({"sha256": digest}))


def test_a_hex_token_that_could_be_a_credential_is_redacted():
    """Same length/charset as a real digest, but keyed like a credential would
    be — the exact ambiguity that made the old hash exemption a leak risk."""
    token = "9f8b3c1a7e2d4f60ab5c8d9e0f1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3"
    out = diagnostics.redact({"api_key": token})
    assert token not in json.dumps(out)


def test_redaction_does_not_mutate_what_it_was_given():
    original = {"path": r"C:\Users\someone\thing.3mf"}
    copy = dict(original)
    diagnostics.redact(original)
    assert original == copy


def test_port_numbers_survive_but_addresses_do_not():
    out = diagnostics.redact({"line": "connected to 10.0.0.5:7125"})
    assert "7125" in out["line"]
    assert "10.0.0.5" not in out["line"]


def test_a_bundle_with_nothing_selected_still_describes_the_environment(tmp_path):
    bundle = diagnostics.collect(data_dir=str(tmp_path))
    assert bundle["schema_version"] == diagnostics.SCHEMA_VERSION
    assert bundle["studio"]["python"]
    assert bundle["studio"]["os"]
    assert "project" not in bundle


def test_a_missing_project_is_described_rather_than_crashing(tmp_path):
    bundle = diagnostics.collect(project_path=str(tmp_path / "not-there.3mf"),
                                 data_dir=str(tmp_path))
    assert bundle["studio"]["python"]
    # The engine reports an unreadable file as a fact, so the section exists and
    # says so. What must never happen is a traceback or a lost bundle.
    project = bundle.get("project")
    assert project is not None
    assert project["traits"]["readable"] is False
    assert bundle["errors"] == []


def test_a_section_that_raises_is_recorded_and_the_rest_survives(tmp_path, monkeypatch):
    def boom(*_args, **_kwargs):
        raise RuntimeError("the printer went away mid-read")

    monkeypatch.setattr(diagnostics, "_printer", boom)
    bundle = diagnostics.collect(host="printer.local", data_dir=str(tmp_path))
    assert bundle["printer"] is None
    assert any("printer:" in e for e in bundle["errors"])
    assert bundle["studio"]["python"]


def test_the_sliced_section_carries_the_job_but_not_the_whole_config(tmp_path):
    job = tmp_path / "job.gcode"
    job.write_text(
        "; generated by Snapmaker Orca 2.3.4 on 2026-08-23 at 10:00:00\n"
        "G1 X1 Y1\n"
        "; filament used [g] = 0.00, 0.36, 0.00, 0.00\n"
        "; total layers count = 12\n"
        "; printer_model = Snapmaker U1\n"
        "; nozzle_diameter = 0.4,0.4,0.4,0.4\n",
        encoding="utf-8")
    bundle = diagnostics.collect(gcode_path=str(job), data_dir=str(tmp_path))
    sliced = bundle["sliced_job"]
    assert sliced["facts"]["printer_model"] == "Snapmaker U1"
    # The full CONFIG_BLOCK is thousands of lines; the bundle must stay sendable.
    assert "config" not in sliced["facts"]
    assert sliced["checks"]["available"] is True


def test_preview_is_exactly_what_build_would_write(tmp_path):
    preview = diagnostics.preview(data_dir=str(tmp_path))
    written = diagnostics.build(out_dir=str(tmp_path), data_dir=str(tmp_path))
    target = Path(written["path"])
    assert target.exists()
    # Same shape; the timestamp is the only thing that legitimately differs.
    on_disk = json.loads(target.read_text(encoding="utf-8"))
    assert set(on_disk) == set(preview["bundle"])
    assert on_disk["studio"] == preview["bundle"]["studio"]


def test_build_writes_where_it_was_told_and_says_so(tmp_path):
    written = diagnostics.build(out_dir=str(tmp_path), data_dir=str(tmp_path))
    assert Path(written["path"]).parent == tmp_path
    assert written["bytes"] > 0
    assert "Nothing has been sent" in written["note"]


def test_the_note_tells_the_user_nothing_was_sent(tmp_path):
    preview = diagnostics.preview(data_dir=str(tmp_path))
    assert "Nothing has been sent anywhere" in preview["note"]
    assert preview["text"]
