#requires -Version 7.0
# Record the 90-second demo from the running application - REWRAPPED ACCEPTANCE-IDENTITY lane.
#
# Nothing here is synthetic. A REWRAPPED acceptance-identity build of Snapmaker Studio (the same shipped payload,
# installed through tools/harness/HarnessLauncher.psm1) is launched with the sample project, driven through the
# documented beats over the Chrome DevTools Protocol (the same mechanism the acceptance harness uses), and the real
# window is captured with FFmpeg's gdigrab. Every frame is the application.
#
# The window title and UI are the production ones (the acceptance build carries the production app); the install
# identity is not, and this lane does not prove the production installer.
#
# Requires: ffmpeg on PATH or passed with -FFmpeg, and a REWRAPPED acceptance installer + its attestation
# (or a verified real installer for the lane to rewrap). There is no installer auto-discovery.
# Uses the same isolation as tools/acceptance/run.ps1 - an isolated WebView2 profile and engine data directory,
# passed only to the child process - so no personal library or recent-file names can appear in the recording.
# The production app must not be running and its update auto-check must be off (or its state file absent).
#
# Usage:
#   pwsh -File tools/demo/record.ps1 -InstallerPath <rewrapped installer> -AttestationPath <its attestation>
#        [-FFmpeg <path>] [-Out <mp4>] [-Short] [-KeepInstall]
#   or: -RealInstaller <path> -ExpectedSha256 <sha256> -SourceVersion <semver> [-Sha256SumsPath <path>]

[CmdletBinding()]
param(
    [string]$InstallerPath,
    [string]$AttestationPath,
    [string]$RealInstaller,
    [string]$ExpectedSha256,
    [string]$Sha256SumsPath,
    [string]$SourceVersion,
    [string]$FFmpeg = "ffmpeg",
    [string]$Out,
    [switch]$Short,
    [switch]$KeepInstall,
    [int]$DebugPort = 9355
)

$ErrorActionPreference = "Stop"
$repo = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
Import-Module (Join-Path $PSScriptRoot "..\harness\HarnessLauncher.psm1") -Force -DisableNameChecking

$laneArgs = @{
    InstallerPath = $InstallerPath; AttestationPath = $AttestationPath
    RealInstaller = $RealInstaller; ExpectedSha256 = $ExpectedSha256; Sha256SumsPath = $Sha256SumsPath; SourceVersion = $SourceVersion
}
$lane = Start-HarnessLane -Name "demo" -Kind demo @laneArgs -DebugPort $DebugPort -KeepInstall:$KeepInstall
$WorkDir = $lane.RunDir
if (-not $Out) { $Out = Join-Path $lane.EvidenceDir "snapmaker-studio-demo.mp4" }
$sample     = Join-Path $repo "examples\demo_u1_showcase.3mf"
$sampleWork = Join-Path $WorkDir "demo_u1_showcase.3mf"
$demoWatch = Join-Path $WorkDir "orca-output"
$demoJob = Join-Path $WorkDir "demo_job.gcode"
$result = $null
$failure = $null
$recorder = $null

try {
Copy-Item $sample $sampleWork -Force

# A sliced job for the second half of the demo. Studio does not slice, so this is
# the one thing the recording cannot produce on camera; everything Studio then
# does with it is real, and this file is shaped exactly like Snapmaker Orca output.
# The engine data directory and WebView2 profile are fresh in every run (a new run
# directory), so the fix ledger in the recording shows this run's work rather than every
# previous take stacked on top of it.
New-Item -ItemType Directory -Force -Path $demoWatch | Out-Null
@'
; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.4 on 2026-08-23 at 10:00:00
; total layer number: 120
; HEADER_BLOCK_END
; EXECUTABLE_BLOCK_START
PRINT_START
M140 S60
M104 T0 S220
T0
;LAYER_CHANGE
;Z:0.2
G1 X10 Y10 E1
T2
;LAYER_CHANGE
;Z:0.4
G1 X20 Y20 E1
PRINT_END
; EXECUTABLE_BLOCK_END

; filament used [g] = 18.40, 0.00, 6.20, 0.00
; total filament used [g] = 24.60
; total layers count = 120
; estimated printing time (normal mode) = 2h 14m 8s

; CONFIG_BLOCK_START
; filament_type = PLA;PLA;PETG;PLA
; filament_colour = #E64B3B;#2D9E59;#1F8CE0;#FFFFFF
; nozzle_diameter = 0.4,0.4,0.4,0.4
; printable_area = 0.5x1,270.5x1,270.5x271,0.5x271
; printer_model = Snapmaker U1
; CONFIG_BLOCK_END
'@ | Set-Content $demoJob -Encoding utf8

# Always install fresh into this run's own install directory. (Reusing whatever was left in a work
# directory once produced a demo of the previous release - the status bar in the recording named a
# version that was no longer the one being shipped.)
Write-Host "Installing the rewrapped acceptance-identity build"
$inst = Install-HarnessBuild -Lane $lane -Which Primary
if ($inst.ExitCode -ne 0) { throw "install failed with exit code $($inst.ExitCode)" }

# Isolation variables reach ONLY the app child process, inside Start-HarnessApp.
$appHandle = Start-HarnessApp -Lane $lane -Arguments @($sampleWork) -SettleSeconds 10 -Label "app"
$app = $appHandle.Process
try {
    # Put the window somewhere predictable so the capture is a consistent size.
    Add-Type @"
using System;
using System.Runtime.InteropServices;
public static class Win {
    [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr h);
    [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr h,int c);
    [DllImport("user32.dll")] public static extern bool SetWindowPos(IntPtr h,IntPtr a,int x,int y,int w,int t,uint f);
    [StructLayout(LayoutKind.Sequential)] public struct RECT { public int Left, Top, Right, Bottom; }
    [StructLayout(LayoutKind.Sequential)] public struct POINT { public int X, Y; }
    [DllImport("user32.dll")] public static extern bool GetClientRect(IntPtr h, out RECT r);
    [DllImport("user32.dll")] public static extern bool ClientToScreen(IntPtr h, ref POINT p);
    [DllImport("user32.dll")] public static extern bool SetProcessDPIAware();
}
"@
    # Without this, this process is DPI-virtualised: every rectangle Windows
    # hands back is in logical units while ffmpeg captures physical pixels, and
    # the capture lands up and to the left of the app — filming a strip of
    # whatever is behind it and cutting off the right-hand side.
    [Win]::SetProcessDPIAware() | Out-Null
    $handle = (Get-Process -Id $app.Id).MainWindowHandle
    [Win]::ShowWindow($handle, 9) | Out-Null      # restore, in case it opened maximised
    # Pin the window topmost at a known rectangle. gdigrab's window mode reads the
    # window DC, which for an occluded or background window can return a stale
    # frame — the first recording came out as 71 seconds of the dashboard that was
    # on screen when capture began. Capturing the screen region instead always
    # reflects what is actually displayed, and pinning the window guarantees the
    # region is the app.
    $x = 40; $y = 40; $w = 1600; $h = 1000
    [Win]::SetWindowPos($handle, [IntPtr](-1), $x, $y, $w, $h, 0x0040) | Out-Null   # HWND_TOPMOST
    [Win]::SetForegroundWindow($handle) | Out-Null
    Start-Sleep -Seconds 2

    # Capture exactly the client area — the page, with no title bar and no drop
    # shadow. An earlier version insetted GetWindowRect by fixed pixel counts;
    # those counts are logical units, the rectangle is physical pixels, and on a
    # scaled display the difference filmed a strip of whatever was behind the app
    # and cut off the right-hand side. GetClientRect plus ClientToScreen gives the
    # true client rectangle in physical pixels, with no arithmetic to get wrong.
    $client = New-Object Win+RECT
    [Win]::GetClientRect($handle, [ref]$client) | Out-Null
    $origin = New-Object Win+POINT
    [Win]::ClientToScreen($handle, [ref]$origin) | Out-Null
    $x = $origin.X; $y = $origin.Y
    $w = $client.Right - $client.Left
    $h = $client.Bottom - $client.Top
    # x264 needs even dimensions.
    if ($w % 2) { $w-- }
    if ($h % 2) { $h-- }
    Write-Host "Capturing ${w}x${h} at ${x},${y}"

    # gdigrab captures the window itself, so nothing else on the desktop is filmed.
    # Recording lands in Matroska first: it tolerates an abruptly ended stream,
    # whereas an MP4 whose moov atom was never written is simply unplayable. The
    # file is remuxed to MP4 once the stream has been closed cleanly.
    $raw = [System.IO.Path]::ChangeExtension($Out, ".mkv")
    $log = Join-Path $WorkDir "ffmpeg.log"
    # ffmpeg is started through the launcher (tracked by pid + start time, stdin kept open so it can be told
    # to quit). Each argument is its own element, so an output path containing a space needs no manual quoting.
    # stderr is drained into a log so a full pipe can never stall the recorder.
    $recorder = Start-HarnessTool -Lane $lane -Tool $FFmpeg -Hidden -RedirectInput -RedirectOutput -Label "ffmpeg" -ArgumentList @(
        "-y", "-loglevel", "warning", "-nostats", "-f", "gdigrab", "-framerate", "30", "-draw_mouse", "1",
        "-offset_x", "$x", "-offset_y", "$y", "-video_size", "${w}x${h}",
        "-i", "desktop",
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "20",
        "-pix_fmt", "yuv420p", $raw
    )
    $ffErr = $recorder.Process.StandardError.ReadToEndAsync()
    $ffOut = $recorder.Process.StandardOutput.ReadToEndAsync()
    Start-Sleep -Seconds 3

    Write-Host "Recording - driving the demo beats"
    $cut = if ($Short) { "short" } else { "full" }
    $r = Invoke-HarnessNode -Lane $lane -ArgumentList @((Join-Path $PSScriptRoot "beats.mjs"), $appHandle.CdpUrl, $cut, $demoJob, $demoWatch)
    $r.Output | ForEach-Object { Write-Host $_ }
    if ($r.ExitCode -ne 0) { throw "the demo beats failed" }

    Start-Sleep -Seconds 2
}
finally {
    # Let ffmpeg close the stream itself ('q' on its stdin). A hard kill mid-write leaves a file
    # that will not play, which is indistinguishable from not recording at all. Only if it does not
    # quit in time is it force-stopped - by its tracked pid and start time, never by name.
    if ($recorder) {
        [void](Stop-HarnessTool -Lane $lane -Handle $recorder -QuitOnStdin -GraceSeconds 15)
        try { if ($ffErr.Wait(3000)) { Set-Content -LiteralPath $log -Value ($ffErr.Result + $ffOut.Result) -Encoding utf8 } } catch { }
        Start-Sleep -Seconds 2
    }
}

$raw = [System.IO.Path]::ChangeExtension($Out, ".mkv")
if (-not (Test-Path $raw)) {
    $log = Join-Path $WorkDir "ffmpeg.log"
    if (Test-Path $log) { Write-Host "--- ffmpeg log ---"; Get-Content $log -Tail 20 }
    throw "no recording was produced"
}

# Remux (no re-encode) into a normal MP4 with the index at the front.
$remux = Invoke-HarnessTool -Lane $lane -Tool $FFmpeg -ArgumentList @("-hide_banner", "-loglevel", "error", "-y", "-i", $raw, "-c", "copy", "-movflags", "+faststart", $Out)
if (-not (Test-Path $Out)) { throw "the recording could not be remuxed to MP4" }

$mb = [math]::Round((Get-Item $Out).Length / 1MB, 2)
Write-Host "Recorded $Out ($mb MB)"
$info = Invoke-HarnessTool -Lane $lane -Tool $FFmpeg -ArgumentList @("-hide_banner", "-i", $Out)
$info.Output | Select-String "Duration|Stream #0"
Remove-Item $raw -ErrorAction SilentlyContinue
}
catch {
    $failure = $_
    Write-Host "FAIL  demo recording aborted: $(Protect-LaneText -Text $_.Exception.Message -Lane $lane)"
}
finally {
    # Always runs, including with -KeepInstall (which skips the uninstall and the recovery): processes, uninstall, journal
    # recovery, production tripwire, lock release.
    $result = Complete-HarnessLane -Lane $lane
}

# Closed-schema lane evidence (fixed codes and counts only); a writer failure FAILS the lane (scrubbed findings/errors are still printed first).
$rc = Publish-HarnessLaneReport -Lane $lane -Result $result -EvidencePath (Join-Path $lane.EvidenceDir "lane-evidence.json") -Failed:([bool]$failure)
if ($KeepInstall) { Write-Host "NOTE  -KeepInstall: the acceptance install and its journal(s) were KEPT (not uninstalled, not recovered). Uninstall it yourself, then for EACH journal run: tools/harness/Repair-Harness.ps1 -RunId <id> -ShortcutDir $($lane.ShortcutDir)   (journal ids: $((@($lane.Phases | ForEach-Object { $_.RunId })) -join ', '))" }
if ($rc -ne 0) { exit 1 }
